services:
  test_app:
    build:
      context: .
      target: coverage
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE}/QualityControl/coverage
        target: /usr/src/app/coverage
        read_only: false