services:
  test_app:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      target: test
    environment:
      NODE_ENV: test
    container_name: qcg-application-test
