version: '3.8'

services:
  database:
    image: "mariadb:10.5.9"
    container_name: qcg-database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-cern}"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./docker/database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./docker/database/populate
        target: /docker-entrypoint-initdb.d
    # Max total time for the container to start 2 mins (20s + 5*20s)
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD:-cern}"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 20s

volumes:
  database-data:
