services:
  test_app:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: .
      target: coverage-ci
    volumes:
      - type: bind
        source: ${GITHUB_WORKSPACE}/QualityControl/coverage
        target: /usr/src/app/coverage
        read_only: false
    container_name: qcg-application-coverage-ci
