version: '3.8'

services:
  database:
    # Pinned to 11.8 LTS version, community support till 04-07-2028, enterprise: 15-10-2033.
    image: "mariadb:10.5.9"
    container_name: qcg-database
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-cern}"
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./docker/database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./docker/database/populate
        target: /docker-entrypoint-initdb.d
    # Max total time for the container to start 40 sec (10s + 6*5s)
    # https://mariadb.com/docs/server/server-management/automated-mariadb-deployment-and-administration/docker-and-mariadb/using-healthcheck-sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  database-data:
