services:
  application:
    build:
      target: development
    environment:
      DATABASE_HOST: database
      DATABASE_LOGGING: "${DATABASE_LOGGING-True}"

    ports:
      - "8080:8080"
    container_name: qcg-application
    volumes:
      - type: bind
        read_only: true
        source: ./lib
        target: /usr/src/app/lib
      - type: bind
        read_only: true
        source: ./public
        target: /usr/src/app/public   

  database:
    image: "mariadb:10.5.9"
    container_name: qcg-database
    environment:
      MYSQL_ROOT_PASSWORD: cern
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        read_only: false
        source: database-data
        target: /var/lib/mysql

volumes:
  database-data:

