export const TokenStatus = {
    ACTIVE: 'active',
    NOT_ACTIVE: 'not-active'
};

export let mockServices = [
  {
    serviceId: '1',
    commonName: 'Service One',
    iat: '2025-05-01T08:00:00Z',
    exp: '2026-05-01T08:00:00Z',
  },
  {
    serviceId: '2',
    commonName: 'Service Two',
    iat: '2024-11-15T10:30:00Z',
    exp: '2025-11-15T10:30:00Z',
  },
  {
    serviceId: '3',
    commonName: 'Service Three',
    iat: '2025-08-20T06:15:00Z',
    exp: '2026-08-20T06:15:00Z',
  },
  {
    serviceId: '4',
    commonName: 'Service Four',
    iat: '2023-12-05T14:00:00Z',
    exp: '2024-12-05T14:00:00Z',
  },
  {
    serviceId: '5',
    commonName: 'Service Five',
    iat: '2025-02-10T09:45:00Z',
    exp: '2026-02-10T09:45:00Z',
  },
  {
    serviceId: '6',
    commonName: 'Service Six',
    iat: '2024-06-18T07:20:00Z',
    exp: '2025-06-18T07:20:00Z',
  },
  {
    serviceId: '7',
    commonName: 'Service Seven',
    iat: '2023-09-22T11:05:00Z',
    exp: '2024-09-22T11:05:00Z',
  },
  {
    serviceId: '8',
    commonName: 'Service Eight',
    iat: '2025-03-30T05:40:00Z',
    exp: '2026-03-30T05:40:00Z',
  },
  {
    serviceId: '9',
    commonName: 'Service Nine',
    iat: '2024-01-12T16:25:00Z',
    exp: '2025-01-12T16:25:00Z',
  },
  {
    serviceId: '10',
    commonName: 'Service Ten',
    iat: '2025-07-04T13:10:00Z',
    exp: '2026-07-04T13:10:00Z',
  },
  {
    serviceId: '11',
    commonName: 'Service Eleven',
    iat: '2023-11-08T19:55:00Z',
    exp: '2024-11-08T19:55:00Z',
  },
  {
    serviceId: '12',
    commonName: 'Service Twelve',
    iat: '2024-04-27T02:30:00Z',
    exp: '2025-04-27T02:30:00Z',
  },
];

export let mockTokens = [
  {
    tokenId: '1',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    exp: '2025-12-01T10:00:00Z',
    last4chars: 'd9f1',
    issuer: 'token-service',
    iat: '2025-05-01T10:00:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '2',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service One'),
    exp: '2025-09-18T08:00:00Z',
    last4chars: 'aa10',
    issuer: 'token-service',
    iat: '2025-04-10T08:00:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '3',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    exp: '2026-01-03T12:00:00Z',
    last4chars: '0042',
    issuer: 'token-service',
    iat: '2025-06-15T12:00:00Z',
    permissions: ['GET', 'POST', 'DELETE'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '4',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Five'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Six'),
    exp: '2025-11-07T15:30:00Z',
    last4chars: '6a1c',
    issuer: 'token-service',
    iat: '2025-03-07T15:30:00Z',
    permissions: ['GET', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '5',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Six'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Three'),
    exp: '2024-12-14T04:45:00Z',
    last4chars: '3fe8',
    issuer: 'token-service',
    iat: '2024-06-14T04:45:00Z',
    permissions: ['GET'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '6',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Seven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    exp: '2025-08-21T09:10:00Z',
    last4chars: 'a92d',
    issuer: 'token-service',
    iat: '2025-02-21T09:10:00Z',
    permissions: ['GET', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '7',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eight'),
    serviceTo: mockServices.find(s => s.commonName === 'Service One'),
    exp: '2026-03-01T22:20:00Z',
    last4chars: 'bb0f',
    issuer: 'token-service',
    iat: '2025-09-01T22:20:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '8',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Nine'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    exp: '2024-10-30T01:15:00Z',
    last4chars: 'e1c4',
    issuer: 'token-service',
    iat: '2024-02-01T01:15:00Z',
    permissions: ['GET'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '9',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Ten'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    exp: '2025-07-04T13:10:00Z',
    last4chars: 'c991',
    issuer: 'token-service',
    iat: '2025-05-01T18:30:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '10',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eleven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Three'),
    exp: '2024-11-08T19:55:00Z',
    last4chars: '11dd',
    issuer: 'token-service',
    iat: '2024-05-08T19:55:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '11',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Twelve'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    exp: '2025-04-27T02:30:00Z',
    last4chars: '8f77',
    issuer: 'token-service',
    iat: '2024-12-27T02:30:00Z',
    permissions: ['GET', 'POST', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '12',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Four'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Ten'),
    exp: '2026-02-18T06:05:00Z',
    last4chars: '59ea',
    issuer: 'token-service',
    iat: '2025-06-18T06:05:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '13',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Nine'),
    exp: '2024-09-12T17:00:00Z',
    last4chars: '72bc',
    issuer: 'token-service',
    iat: '2024-03-12T17:00:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '14',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eleven'),
    exp: '2025-01-19T14:45:00Z',
    last4chars: '5a4e',
    issuer: 'token-service',
    iat: '2024-07-19T14:45:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.NOT_ACTIVE,
  },
  {
    tokenId: '15',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eight'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Twelve'),
    exp: '2026-05-09T20:25:00Z',
    last4chars: '04c5',
    issuer: 'token-service',
    iat: '2025-09-09T20:25:00Z',
    permissions: ['GET', 'POST', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '16',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Three'),
    exp: '2026-06-01T08:00:00Z',
    last4chars: '16a1',
    issuer: 'token-service',
    iat: '2025-06-01T08:00:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '17',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    exp: '2026-06-05T09:15:00Z',
    last4chars: '17b2',
    issuer: 'token-service',
    iat: '2025-06-05T09:15:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '18',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    exp: '2026-06-10T10:30:00Z',
    last4chars: '18c3',
    issuer: 'token-service',
    iat: '2025-06-10T10:30:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '19',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Four'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Six'),
    exp: '2026-06-12T11:45:00Z',
    last4chars: '19d4',
    issuer: 'token-service',
    iat: '2025-06-12T11:45:00Z',
    permissions: ['GET', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '20',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Five'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Seven'),
    exp: '2026-06-15T12:00:00Z',
    last4chars: '20e5',
    issuer: 'token-service',
    iat: '2025-06-15T12:00:00Z',
    permissions: ['GET', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '21',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Six'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eight'),
    exp: '2026-06-18T13:10:00Z',
    last4chars: '21f6',
    issuer: 'token-service',
    iat: '2025-06-18T13:10:00Z',
    permissions: ['GET', 'POST', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '22',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Seven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Nine'),
    exp: '2026-06-20T14:20:00Z',
    last4chars: '22g7',
    issuer: 'token-service',
    iat: '2025-06-20T14:20:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '23',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eight'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Ten'),
    exp: '2026-06-22T15:35:00Z',
    last4chars: '23h8',
    issuer: 'token-service',
    iat: '2025-06-22T15:35:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '24',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Nine'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eleven'),
    exp: '2026-06-25T16:50:00Z',
    last4chars: '24i9',
    issuer: 'token-service',
    iat: '2025-06-25T16:50:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '25',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Ten'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Twelve'),
    exp: '2026-06-28T17:05:00Z',
    last4chars: '25j0',
    issuer: 'token-service',
    iat: '2025-06-28T17:05:00Z',
    permissions: ['GET', 'POST', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '26',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eleven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service One'),
    exp: '2026-07-01T18:15:00Z',
    last4chars: '26k1',
    issuer: 'token-service',
    iat: '2025-07-01T18:15:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '27',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Twelve'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    exp: '2026-07-03T19:25:00Z',
    last4chars: '27l2',
    issuer: 'token-service',
    iat: '2025-07-03T19:25:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '28',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    exp: '2026-07-05T20:35:00Z',
    last4chars: '28m3',
    issuer: 'token-service',
    iat: '2025-07-05T20:35:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '29',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    exp: '2026-07-08T21:45:00Z',
    last4chars: '29n4',
    issuer: 'token-service',
    iat: '2025-07-08T21:45:00Z',
    permissions: ['GET', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '30',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Six'),
    exp: '2026-07-10T22:55:00Z',
    last4chars: '30o5',
    issuer: 'token-service',
    iat: '2025-07-10T22:55:00Z',
    permissions: ['GET', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '31',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Four'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Seven'),
    exp: '2026-07-12T23:59:00Z',
    last4chars: '31p6',
    issuer: 'token-service',
    iat: '2025-07-12T23:59:00Z',
    permissions: ['GET', 'POST', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '32',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Five'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eight'),
    exp: '2026-07-15T07:05:00Z',
    last4chars: '32q7',
    issuer: 'token-service',
    iat: '2025-07-15T07:05:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '33',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Six'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Nine'),
    exp: '2026-07-17T08:15:00Z',
    last4chars: '33r8',
    issuer: 'token-service',
    iat: '2025-07-17T08:15:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '34',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Seven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Ten'),
    exp: '2026-07-19T09:25:00Z',
    last4chars: '34s9',
    issuer: 'token-service',
    iat: '2025-07-19T09:25:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '35',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eight'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eleven'),
    exp: '2026-07-21T10:35:00Z',
    last4chars: '35t0',
    issuer: 'token-service',
    iat: '2025-07-21T10:35:00Z',
    permissions: ['GET', 'POST', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '36',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Nine'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Twelve'),
    exp: '2026-07-23T11:45:00Z',
    last4chars: '36u1',
    issuer: 'token-service',
    iat: '2025-07-23T11:45:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '37',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Ten'),
    serviceTo: mockServices.find(s => s.commonName === 'Service One'),
    exp: '2026-07-25T12:55:00Z',
    last4chars: '37v2',
    issuer: 'token-service',
    iat: '2025-07-25T12:55:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '38',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Eleven'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    exp: '2026-07-27T14:05:00Z',
    last4chars: '38w3',
    issuer: 'token-service',
    iat: '2025-07-27T14:05:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '39',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Twelve'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Three'),
    exp: '2026-07-29T15:15:00Z',
    last4chars: '39x4',
    issuer: 'token-service',
    iat: '2025-07-29T15:15:00Z',
    permissions: ['GET', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '40',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    exp: '2026-08-01T16:25:00Z',
    last4chars: '40y5',
    issuer: 'token-service',
    iat: '2025-08-01T16:25:00Z',
    permissions: ['GET', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '41',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Six'),
    exp: '2026-08-03T17:35:00Z',
    last4chars: '41z6',
    issuer: 'token-service',
    iat: '2025-08-03T17:35:00Z',
    permissions: ['GET', 'POST', 'PATCH'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '42',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Seven'),
    exp: '2026-08-05T18:45:00Z',
    last4chars: '42a7',
    issuer: 'token-service',
    iat: '2025-08-05T18:45:00Z',
    permissions: ['GET', 'DELETE'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '43',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Four'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Eight'),
    exp: '2026-08-07T19:55:00Z',
    last4chars: '43b8',
    issuer: 'token-service',
    iat: '2025-08-07T19:55:00Z',
    permissions: ['GET', 'POST', 'PUT'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '44',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Five'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Nine'),
    exp: '2026-08-09T21:05:00Z',
    last4chars: '44c9',
    issuer: 'token-service',
    iat: '2025-08-09T21:05:00Z',
    permissions: ['GET'],
    status: TokenStatus.ACTIVE,
  },
  {
    tokenId: '45',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Six'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Ten'),
    exp: '2026-08-11T22:15:00Z',
    last4chars: '45d0',
    issuer: 'token-service',
    iat: '2025-08-11T22:15:00Z',
    permissions: ['GET', 'POST'],
    status: TokenStatus.ACTIVE,
  },
];

export const mockTokenLogs = {
    '1': [
      { id: '1-1', message: 'Token issued', timestamp: '2025-05-01T10:00:00Z' },
      { id: '1-2', message: 'Token used', timestamp: '2025-08-11T09:45:00Z' },
    ],
    '2': [
      { id: '2-1', message: 'Token issued', timestamp: '2025-04-10T08:00:00Z' },
      { id: '2-2', message: 'Token used', timestamp: '2025-05-20T12:20:00Z' },
    ],
    '3': [
        { id: '3-1', message: 'Token issued', timestamp: '2025-06-15T12:00:00Z' },
        { id: '3-2', message: 'Token used', timestamp: '2025-09-01T18:30:00Z' },
        { id: '3-3', message: 'Token revoked', timestamp: '2025-10-04T07:15:00Z' },
    ],
};



export let mockServiceRoutes = [
  {
    routeId: 'route-001',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    permissions: ['GET', 'POST'],
  },
  {
    routeId: 'route-002',
    serviceFrom: mockServices.find(s => s.commonName === 'Service One'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    permissions: ['GET'],
  },
  {
    routeId: 'route-003',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service One'),
    permissions: ['GET', 'DELETE'],
  },
  {
    routeId: 'route-004',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Two'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    permissions: ['GET', 'POST'],
  },
  {
    routeId: 'route-005',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Two'),
    permissions: ['GET', 'PUT'],
  },
  {
    routeId: 'route-006',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Three'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Four'),
    permissions: ['GET'],
  },
  {
    routeId: 'route-007',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Four'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Five'),
    permissions: ['GET', 'POST', 'DELETE'],
  },
  {
    routeId: 'route-008',
    serviceFrom: mockServices.find(s => s.commonName === 'Service Five'),
    serviceTo: mockServices.find(s => s.commonName === 'Service Three'),
    permissions: ['GET', 'PATCH'],
  },
];
