syntax = "proto3";

package webui.tokenization;

// ======================================
//                SERVICES
// ======================================

// Central System service handling duplex communication with wrapper client
service CentralSystem {
    rpc ClientStream(stream Payload) returns (stream Payload);
}

// ======================================
//                MESSAGES
// ======================================

// Simulates an empty message because protobuffer doesn't support void
message EmptyMessage {}

// Message with token and target address binded to it
message Token {
    string token = 1;
    string targetAddress = 2;
}

// Stream message that can contain one of specific messages
message Payload {
    // Message event type
    MessageEvent event = 1;
    // Data related to specific event type
    oneof data {
        EmptyMessage emptyMessage = 2;
        Token newToken = 3;
        Token revokeToken = 4;
    }
}

// ======================================
//                 ENUMS
// ======================================

enum MessageEvent {
    // Default value, represents an empty event
    MESSAGE_EVENT_EMPTY = 0;

    // New token message type, contains a new token and target address
    MESSAGE_EVENT_NEW_TOKEN = 1;

    // Revoke token message type, contains a token to be revoked
    MESSAGE_EVENT_REVOKE_TOKEN = 2;
}
