/**
 * @license
 * Copyright 2019-2020 CERN and copyright holders of ALICE O2.
 * See http://alice-o2.web.cern.ch/copyright for details of the copyright holders.
 * All rights not expressly granted are reserved.
 *
 * This software is distributed under the terms of the GNU General Public
 * License v3 (GPL Version 3), copied verbatim in the file "COPYING".
 *
 * In applying this license CERN does not waive the privileges and immunities
 * granted to it by virtue of its status as an Intergovernmental Organization
 * or submit itself to any jurisdiction.
 */

syntax = "proto3";

package webui.tokenization;

// ======================================
//                SERVICES
// ======================================

// Central System service handling duplex communication with wrapper client
service CentralSystem {
    rpc ClientStream(stream Payload) returns (stream Payload);
}

// ======================================
//                MESSAGES
// ======================================

// Simulates an empty message because protobuffer doesn't support void
message EmptyMessage {}

// Message with token and target address binded to it
message Token {
    string token = 1;
    string targetAddress = 2;
    ConnectionDirection connectionDirection = 3;
}

// Stream message that can contain one of specific messages
message Payload {
    // Message event type
    MessageEvent event = 1;
    
    // Data related to specific event type
    oneof data {
        EmptyMessage emptyMessage = 2;
        Token payload = 3;
    }
}

// ======================================
//                 ENUMS
// ======================================

enum MessageEvent {
    // Unspecified event type
    MESSAGE_EVENT_UNSPECIFIED = 0;

    // Default value, represents an empty event
    MESSAGE_EVENT_EMPTY = 1;

    // New token message type, contains a new token and target address
    MESSAGE_EVENT_NEW_TOKEN = 2;

    // Revoke token message type, contains a token to be revoked
    MESSAGE_EVENT_REVOKE_TOKEN = 3;
}

enum ConnectionDirection {
    // Unspecified direction
    UNSPECIFIED = 0;

    // Direction from client to server
    SENDING = 1;

    // Direction from server to client
    RECEIVING = 2;

    // Duplex connection, both sending and receiving
    DUPLEX = 3;
}