/// Event types for vault operations
export enum EventType {
  SIGN_TOKEN_VAULT = "SIGN_TOKEN_VAULT",
  LOGIN_VAULT = "LOGIN_VAULT",
  RENEW_VAULT_TOKEN = "RENEW_VAULT_TOKEN",
  GET_CREDENTIAL_VAULT = "GET_CREDENTIAL_VAULT",
  CREATE_OR_UPDATE_CREDENTIAL_VAULT = "CREATE_OR_UPDATE_CREDENTIAL_VAULT",
}
