/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.o2control.EnvironmentInfo', null, global);
goog.exportSymbol('proto.o2control.ShortTaskInfo', null, global);
goog.exportSymbol('proto.o2control.TaskDeploymentInfo', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.o2control.EnvironmentInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.o2control.EnvironmentInfo.repeatedFields_, null);
};
goog.inherits(proto.o2control.EnvironmentInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.o2control.EnvironmentInfo.displayName = 'proto.o2control.EnvironmentInfo';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.o2control.EnvironmentInfo.repeatedFields_ = [4,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.o2control.EnvironmentInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.o2control.EnvironmentInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.o2control.EnvironmentInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.o2control.EnvironmentInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    createdwhen: jspb.Message.getFieldWithDefault(msg, 2, 0),
    state: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tasksList: jspb.Message.toObjectList(msg.getTasksList(),
    proto.o2control.ShortTaskInfo.toObject, includeInstance),
    rootrole: jspb.Message.getFieldWithDefault(msg, 5, ""),
    currentrunnumber: jspb.Message.getFieldWithDefault(msg, 6, 0),
    defaultsMap: (f = msg.getDefaultsMap()) ? f.toObject(includeInstance, undefined) : [],
    varsMap: (f = msg.getVarsMap()) ? f.toObject(includeInstance, undefined) : [],
    uservarsMap: (f = msg.getUservarsMap()) ? f.toObject(includeInstance, undefined) : [],
    numberofflps: jspb.Message.getFieldWithDefault(msg, 10, 0),
    includeddetectorsList: jspb.Message.getRepeatedField(msg, 11),
    description: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.o2control.EnvironmentInfo}
 */
proto.o2control.EnvironmentInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.o2control.EnvironmentInfo;
  return proto.o2control.EnvironmentInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.o2control.EnvironmentInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.o2control.EnvironmentInfo}
 */
proto.o2control.EnvironmentInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatedwhen(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 4:
      var value = new proto.o2control.ShortTaskInfo;
      reader.readMessage(value,proto.o2control.ShortTaskInfo.deserializeBinaryFromReader);
      msg.addTasks(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRootrole(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCurrentrunnumber(value);
      break;
    case 7:
      var value = msg.getDefaultsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 8:
      var value = msg.getVarsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 9:
      var value = msg.getUservarsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumberofflps(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addIncludeddetectors(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.o2control.EnvironmentInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.o2control.EnvironmentInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.o2control.EnvironmentInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.o2control.EnvironmentInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreatedwhen();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTasksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.o2control.ShortTaskInfo.serializeBinaryToWriter
    );
  }
  f = message.getRootrole();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCurrentrunnumber();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getDefaultsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getVarsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getUservarsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getNumberofflps();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getIncludeddetectorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.o2control.EnvironmentInfo.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.o2control.EnvironmentInfo.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 createdWhen = 2;
 * @return {number}
 */
proto.o2control.EnvironmentInfo.prototype.getCreatedwhen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.o2control.EnvironmentInfo.prototype.setCreatedwhen = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string state = 3;
 * @return {string}
 */
proto.o2control.EnvironmentInfo.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.o2control.EnvironmentInfo.prototype.setState = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ShortTaskInfo tasks = 4;
 * @return {!Array.<!proto.o2control.ShortTaskInfo>}
 */
proto.o2control.EnvironmentInfo.prototype.getTasksList = function() {
  return /** @type{!Array.<!proto.o2control.ShortTaskInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.o2control.ShortTaskInfo, 4));
};


/** @param {!Array.<!proto.o2control.ShortTaskInfo>} value */
proto.o2control.EnvironmentInfo.prototype.setTasksList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.o2control.ShortTaskInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.o2control.ShortTaskInfo}
 */
proto.o2control.EnvironmentInfo.prototype.addTasks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.o2control.ShortTaskInfo, opt_index);
};


proto.o2control.EnvironmentInfo.prototype.clearTasksList = function() {
  this.setTasksList([]);
};


/**
 * optional string rootRole = 5;
 * @return {string}
 */
proto.o2control.EnvironmentInfo.prototype.getRootrole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.o2control.EnvironmentInfo.prototype.setRootrole = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 currentRunNumber = 6;
 * @return {number}
 */
proto.o2control.EnvironmentInfo.prototype.getCurrentrunnumber = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.o2control.EnvironmentInfo.prototype.setCurrentrunnumber = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * map<string, string> defaults = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.o2control.EnvironmentInfo.prototype.getDefaultsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


proto.o2control.EnvironmentInfo.prototype.clearDefaultsMap = function() {
  this.getDefaultsMap().clear();
};


/**
 * map<string, string> vars = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.o2control.EnvironmentInfo.prototype.getVarsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


proto.o2control.EnvironmentInfo.prototype.clearVarsMap = function() {
  this.getVarsMap().clear();
};


/**
 * map<string, string> userVars = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.o2control.EnvironmentInfo.prototype.getUservarsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      null));
};


proto.o2control.EnvironmentInfo.prototype.clearUservarsMap = function() {
  this.getUservarsMap().clear();
};


/**
 * optional int32 numberOfFlps = 10;
 * @return {number}
 */
proto.o2control.EnvironmentInfo.prototype.getNumberofflps = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.o2control.EnvironmentInfo.prototype.setNumberofflps = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * repeated string includedDetectors = 11;
 * @return {!Array.<string>}
 */
proto.o2control.EnvironmentInfo.prototype.getIncludeddetectorsList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array.<string>} value */
proto.o2control.EnvironmentInfo.prototype.setIncludeddetectorsList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.o2control.EnvironmentInfo.prototype.addIncludeddetectors = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


proto.o2control.EnvironmentInfo.prototype.clearIncludeddetectorsList = function() {
  this.setIncludeddetectorsList([]);
};


/**
 * optional string description = 12;
 * @return {string}
 */
proto.o2control.EnvironmentInfo.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.o2control.EnvironmentInfo.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.o2control.ShortTaskInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.o2control.ShortTaskInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.o2control.ShortTaskInfo.displayName = 'proto.o2control.ShortTaskInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.o2control.ShortTaskInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.o2control.ShortTaskInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.o2control.ShortTaskInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.o2control.ShortTaskInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    locked: jspb.Message.getFieldWithDefault(msg, 2, false),
    taskid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    status: jspb.Message.getFieldWithDefault(msg, 4, ""),
    state: jspb.Message.getFieldWithDefault(msg, 5, ""),
    classname: jspb.Message.getFieldWithDefault(msg, 6, ""),
    deploymentinfo: (f = msg.getDeploymentinfo()) && proto.o2control.TaskDeploymentInfo.toObject(includeInstance, f),
    pid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    sandboxstdout: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.o2control.ShortTaskInfo}
 */
proto.o2control.ShortTaskInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.o2control.ShortTaskInfo;
  return proto.o2control.ShortTaskInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.o2control.ShortTaskInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.o2control.ShortTaskInfo}
 */
proto.o2control.ShortTaskInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setLocked(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassname(value);
      break;
    case 7:
      var value = new proto.o2control.TaskDeploymentInfo;
      reader.readMessage(value,proto.o2control.TaskDeploymentInfo.deserializeBinaryFromReader);
      msg.setDeploymentinfo(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSandboxstdout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.o2control.ShortTaskInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.o2control.ShortTaskInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.o2control.ShortTaskInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.o2control.ShortTaskInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLocked();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTaskid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getClassname();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDeploymentinfo();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.o2control.TaskDeploymentInfo.serializeBinaryToWriter
    );
  }
  f = message.getPid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSandboxstdout();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool locked = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.o2control.ShortTaskInfo.prototype.getLocked = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.o2control.ShortTaskInfo.prototype.setLocked = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string taskId = 3;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getTaskid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setTaskid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string status = 4;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setStatus = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string state = 5;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setState = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string className = 6;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getClassname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setClassname = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional TaskDeploymentInfo deploymentInfo = 7;
 * @return {?proto.o2control.TaskDeploymentInfo}
 */
proto.o2control.ShortTaskInfo.prototype.getDeploymentinfo = function() {
  return /** @type{?proto.o2control.TaskDeploymentInfo} */ (
    jspb.Message.getWrapperField(this, proto.o2control.TaskDeploymentInfo, 7));
};


/** @param {?proto.o2control.TaskDeploymentInfo|undefined} value */
proto.o2control.ShortTaskInfo.prototype.setDeploymentinfo = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.o2control.ShortTaskInfo.prototype.clearDeploymentinfo = function() {
  this.setDeploymentinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.o2control.ShortTaskInfo.prototype.hasDeploymentinfo = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string pid = 8;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getPid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setPid = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string sandboxStdout = 9;
 * @return {string}
 */
proto.o2control.ShortTaskInfo.prototype.getSandboxstdout = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/** @param {string} value */
proto.o2control.ShortTaskInfo.prototype.setSandboxstdout = function(value) {
  jspb.Message.setProto3StringField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.o2control.TaskDeploymentInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.o2control.TaskDeploymentInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.o2control.TaskDeploymentInfo.displayName = 'proto.o2control.TaskDeploymentInfo';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.o2control.TaskDeploymentInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.o2control.TaskDeploymentInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.o2control.TaskDeploymentInfo} msg The msg instance to transform.
 * @return {!Object}
 */
proto.o2control.TaskDeploymentInfo.toObject = function(includeInstance, msg) {
  var obj = {
    hostname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agentid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    offerid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    executorid: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.o2control.TaskDeploymentInfo}
 */
proto.o2control.TaskDeploymentInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.o2control.TaskDeploymentInfo;
  return proto.o2control.TaskDeploymentInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.o2control.TaskDeploymentInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.o2control.TaskDeploymentInfo}
 */
proto.o2control.TaskDeploymentInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHostname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgentid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOfferid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setExecutorid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.o2control.TaskDeploymentInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.o2control.TaskDeploymentInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.o2control.TaskDeploymentInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.o2control.TaskDeploymentInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHostname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAgentid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOfferid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExecutorid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string hostname = 1;
 * @return {string}
 */
proto.o2control.TaskDeploymentInfo.prototype.getHostname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.o2control.TaskDeploymentInfo.prototype.setHostname = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agentId = 2;
 * @return {string}
 */
proto.o2control.TaskDeploymentInfo.prototype.getAgentid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.o2control.TaskDeploymentInfo.prototype.setAgentid = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string offerId = 3;
 * @return {string}
 */
proto.o2control.TaskDeploymentInfo.prototype.getOfferid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.o2control.TaskDeploymentInfo.prototype.setOfferid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string executorId = 4;
 * @return {string}
 */
proto.o2control.TaskDeploymentInfo.prototype.getExecutorid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.o2control.TaskDeploymentInfo.prototype.setExecutorid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.o2control);
