export const downloadMockLayout1 =
{
  id: '68de787140445a815bed58ce',
  name: 'jasper Layout',
  owner_id: 883859,
  owner_name: 'Jasper Houweling',
  description: '',
  displayTimestamp: false,
  autoTabChange: 0,
  tabs: [
    {
      id: '68de7871b410c936e50d8a35',
      name: 'main',
      objects: [
        {
          id: 'a379543d-a93c-11ef-9af4-0aa14016a1a2',
          x: 0,
          y: 0,
          h: 1,
          w: 1,
          name: 'qc/CPV/MO/NoiseOnFLP/BadChannelMapM2',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
        {
          id: '90c5335a-098d-11ee-ac92-0aa14016a1a2',
          x: 1,
          y: 0,
          h: 1,
          w: 1,
          name: 'qc/CPV/MO/NoiseOnFLP/DigitFreqM3',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
      ],
      columns: 2,
    },
    {
      id: '68f63c82360430da6e2796df',
      name: 'mft',
      objects: [
        {
          id: 'f3accff9-ae7b-11f0-b850-0aa14520a1a2',
          x: 0,
          y: 0,
          h: 1,
          w: 1,
          name: 'qc/CTP/MO/CcdbInspector/ObjectsStatus',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
        {
          id: 'e16fe7d5-f618-11ed-a4d4-808d4d66a1a2',
          x: 1,
          y: 0,
          h: 1,
          w: 1,
          name: 'qc/FOC/MO/RawTask/HitmapPadASIC_3',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
        {
          id: 'e13de1c6-f618-11ed-a4d4-808d4d66a1a2',
          x: 2,
          y: 0,
          h: 1,
          w: 1,
          name: 'qc/FOC/MO/RawTask/CRUcounter',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
        {
          id: '208b98aa-ae7c-11f0-b866-0aa14414a1a2',
          x: 0,
          y: 1,
          h: 1,
          w: 1,
          name: 'qc/ITS/MO/FHRTask/General/ErrorPlots',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
        {
          id: 'be8c0940-2d1e-11ec-b08a-0aa14028a1a5',
          x: 1,
          y: 1,
          h: 1,
          w: 1,
          name: 'qc/FV0/MO/CalibrationTask/Calibrated_time',
          options: [],
          autoSize: false,
          ignoreDefaults: false,
        },
      ],
      columns: 3,
    },
  ],
  collaborators: [],
};
