services:
  install-backend:
    image: node:22-alpine
    working_dir: /var/workspace
    volumes:
      - ./backend:/var/workspace
    command: ['npm', 'install', '--no-save', '--silent']

  backend:
    image: node:22-alpine
    working_dir: /var/workspace/central-system
    volumes:
      - ./backend:/var/workspace
    command: ['npm', 'run', 'dev']
    healthcheck:
      interval: 1s
      test:
        [
          'CMD-SHELL',
          'node',
          '-c',
          'node --input-type=module -e "process.exit((await fetch(''http://backend:8080/api/healthcheck'')).ok === true ? 0 : 1)"',
        ]
    depends_on:
      install-backend:
        condition: service_completed_successfully

  prod-container:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      backend:
        condition: service_healthy

  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./webapp/tests:/var/workspace/tests
    depends_on:
      prod-container:
        condition: service_healthy
