services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - '127.0.0.1:8200:9300'
      - '127.0.0.1:8201:9301'
    environment:
      VAULT_LOCAL_CONFIG: |
        ui = true
        disable_mlock = true
        cluster_name = "dev-raft"

        api_addr     = "https://vault.local:8200"
        cluster_addr = "https://vault.local:8201"

        listener "tcp" {
          address         = "0.0.0.0:9300"
          cluster_address = "0.0.0.0:9301"
          tls_cert_file      = "/vault/config/vault.crt"
          tls_key_file       = "/vault/config/vault.key"
          tls_client_ca_file = "/vault/config/ca.crt"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "node1"
        }
    entrypoint:
      - /bin/sh
      - -lc
      - |
        set -e
        docker-entrypoint.sh >/dev/null 2>&1 || true
        exec vault server -config=/vault/config/local.json
    networks:
      default:
        aliases:
          - vault.local
    networks:
      default:
        aliases:
          - vault.local
    volumes:
      - type: volume
        source: vault-data
        target: /vault/data

      - ./docker/vault/vault.crt:/vault/config/vault.crt:ro
      - ./docker/vault/vault.key:/vault/config/vault.key:ro
      - ./docker/ca/ca.crt:/vault/config/ca.crt:ro
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  vault-setup:
    image: hashicorp/vault:latest
    depends_on:
      vault:
        condition: service_started
    environment:
      VAULT_ADDR: https://vault.local:9300
      VAULT_TLS_SERVER_NAME: vault.local
    volumes:
      - vault-data:/vault/data
      - ./docker/vault/vault.crt:/vault/config/vault.crt:ro
      - ./docker/vault/vault.key:/vault/config/vault.key:ro
      - ./docker/vault/ca.crt:/vault/config/ca.crt:ro
      - ./docker/vault/vault-setup.sh:/vault-setup.sh:ro
      - ./docker/vault/central-system.crt:/vault/config/central-system-client.crt:ro
    entrypoint: ['/bin/sh', '-lc']
    command: ['/vault-setup.sh']
    restart: 'on-failure'

  database:
    image: 'mariadb:10.5.9'
    container_name: tokenization-database
    environment:
      MYSQL_ROOT_PASSWORD: 'cern'
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./docker/database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./docker/database/populate
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '--user=root',
          '--password=cern',
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

volumes:
  database-data:
  vault-data:
