services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "127.0.0.1:8200:9300"
      - "127.0.0.1:8201:9301"
    environment:
      VAULT_LOCAL_CONFIG: |
        ui = true
        disable_mlock = true
        cluster_name = "dev-raft"

        api_addr     = "https://vault.local:8200"
        cluster_addr = "https://vault.local:8201"

        listener "tcp" {
          address         = "0.0.0.0:9300"   
          cluster_address = "0.0.0.0:9301"
          tls_cert_file   = "/vault/config/vault.crt"
          tls_key_file    = "/vault/config/vault.key"
          tls_client_ca_file = "/vault/config/ca.crt"
        }

        storage "raft" {
          path    = "/vault/data"
          node_id = "node1"
        }
    entrypoint:
      - /bin/sh
      - -lc
      - |
        set -e
        docker-entrypoint.sh >/dev/null 2>&1 || true
        exec vault server -config=/vault/config/local.json
    networks:
      default:
        aliases:
          - vault.local
    volumes:
      - ./backend/central-system/vault/vault-data:/vault/data
      - ./backend/central-system/vault/vault.crt:/vault/config/vault.crt:ro
      - ./backend/central-system/vault/vault.key:/vault/config/vault.key:ro
      - ./backend/central-system/ca/ca.crt:/vault/config/ca.crt:ro
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  vault-unseal:
    image: curlimages/curl:8.9.1
    depends_on:
      vault:
        condition: service_started
    environment:
      # inside docker: talk to container port 9300 using alias that matches SAN
      VAULT_ADDR: https://vault.local:9300
      VAULT_UNSEAL_KEY: "/Ljh14bkF2VAkxII4bQevZQAnNbNHeg2qK3ND7CL3lU="
    volumes:
      - ./backend/central-system/ca/ca.crt:/ca.crt:ro
      - ./backend/central-system/vault/unseal.sh:/unseal.sh:ro
    entrypoint: ["/bin/sh","-lc"]
    command: ["/unseal.sh"]
    restart: "no"
  database:
    image: mariadb:10.5.9
    environment:
      MYSQL_ROOT_PASSWORD: cern
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - type: bind
        read_only: false
        source: ./database/data
        target: /var/lib/mysql

volumes:
  database-data:
