services:
  install-backend:
    image: node:22-alpine
    working_dir: /var/workspace/central-system
    volumes:
      - ./backend:/var/workspace
    command: ['npm', 'install', '--no-save', '--silent']
  backend:
    image: node:22-alpine
    working_dir: /var/workspace/central-system
    volumes:
      - ./backend:/var/workspace
    env_file:
      - ./backend/central-system/.env
    command: ['npm', 'run', 'dev']
    healthcheck:
      interval: 1s
      test:
        [
          'CMD-SHELL',
          'node',
          '-c',
          'node --input-type=module -e "process.exit((await fetch(''http://backend:8080/api/healthcheck'')).ok === true ? 0 : 1)"',
        ]
    depends_on:
      install-backend:
        condition: service_completed_successfully
      database:
        condition: service_healthy

  prod-container:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/']
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - 8080:80
    depends_on:
      install-backend:
        condition: service_completed_successfully
      database:
        condition: service_healthy
      vault-setup:
        condition: service_completed_successfully

  ui-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - ./webapp/tests:/var/workspace/tests
    depends_on:
      prod-container:
        condition: service_healthy

  database:
    image: 'mariadb:10.5.9'
    container_name: tokenization-database
    environment:
      MYSQL_ROOT_PASSWORD: 'cern'
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        read_only: true
        source: ./docker/database/configuration
        target: /etc/mysql/conf.d
      - type: bind
        read_only: true
        source: ./docker/database/populate
        target: /docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '--user=root',
          '--password=cern',
        ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    restart: unless-stopped

volumes:
  database-data:
