name: Configuration
on:
  pull_request:
    paths:
      - 'Configuration/**/*'
      - '.github/workflows/configuration.yml'
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  formatting-check:
    name: Check prettier formatting rules on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: (cd Configuration/webapp; npm ci )
      - run: (cd Configuration/webapp; npm run prettier-check )
  lint-check:
    name: Check eslint rules on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - run: (cd Configuration/webapp; npm ci )
      - run: (cd Configuration/webapp; npm run typecheck ) # generate .react-router directory
      - run: (cd Configuration/webapp; npm run eslint )
  test:
    name: Run tests 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - name: Install backend (Control) dependencies
        run: (cd Control; npm ci)
      - name: Install frontend (Configuration) dependencies
        run: (cd Configuration/webapp; npm ci)
      - name: Copy backend config file
        run: cp Control/config-default.js Control/config.js
      - name: Modify backend config port
        run: | 
          sed -i 's/port: 8080,/port: 8081,/' Control/config.js
      - name: Start backend (Control) in background
        run: (cd Control; npm start &)
      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:8081 --timeout 120000
      - name: Start frontend (Configuration) in background
        run: (cd Configuration; docker compose up -d)
      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:8080 --timeout 300000
      - name: Run frontend (Configuration) tests
        run: (cd Configuration/webapp; npm run mocha)
