name: Control
on:
  pull_request:
    paths:
      - 'Control/**'
      - '.github/workflows/control.yml'
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  test:
    name: Tests on macos-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: (cd Control; npm ci )
      - run: (cd Control; npm test )
  coverage:
    name: Tests & coverage on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: (cd Control; npm ci )
      - run: (cd Control; npm run coverage )
      - run: (cd Control; ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov)
      - name: Send codecov report for Control
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets. NEW_CODECOV_TOKEN }}
          flags: control
          fail_ci_if_error: true
