name: QualityControl
on:
  pull_request:
    paths:
      - 'QualityControl/**/*'
      - '.github/workflows/qc.yml'
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  lint-check:
    name: Check eslint rules on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd QualityControl; npm ci )
      - run: (cd QualityControl; npm run lint )
  test:
    name: Tests on ubuntu-latest only if lint-check passes
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd QualityControl; npm run docker-test)

  coverage:
    name: Tests and generate lcov reoprt coverage on ubuntu-latest
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - name: Checkout Repository
        uses: actions/@checkout@v4
      - name: Create Coverage Directory
        run: mkdir -p QualityControl/coverage
      - run: (cd QualityControl; npm run docker-coverage )
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./QualityControl/coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
