name: QualityControl
on:
  pull_request:
    paths:
      - 'QualityControl/**/*'
      - '.github/workflows/qc.yml'
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  lint-check:
    name: Check eslint rules on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd QualityControl; npm ci )
      - run: (cd QualityControl; npm run lint )
  test:
    name: Tests on ubuntu-latest only if lint-check passes
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - uses: actions/checkout@v4
      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.11
        with:
          mysql database: 'qcg_test_db' 
          mysql root password: 'testpassword'
          mysql user: 'qcg_test_user'
          mysql password: 'testpassword'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd QualityControl; npm ci)
      - run: (cd QualityControl; npm run test)

  coverage:
    name: Tests and generate lcov reoprt coverage on ubuntu-latest
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd QualityControl; npm ci )
      - run: (cd QualityControl; npm run coverage-lcov )
      - name: Send codecov report for QualityControl
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: qualitycontrol
          fail_ci_if_error: true
