name: Tokenization
on:
  pull_request:
    paths:
      - 'Tokenization/**/*'
      - '.github/workflows/tokenization.yml'
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  lint-check-backend:
    name: Check eslint rules for backend on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@vk
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd Tokenization/backend; npm i)      
  lint-check-webapp:
    name: Check eslint rules for webapp on ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd Tokenization/webapp; npm i )
      - run: (cd Tokenization/webapp; npm run typecheck)
      - run: (cd Tokenization/webapp; npm run lint)

  ui-test:
    name: UI-tests for webapp application
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: (cd Tokenization/webapp; npm run docker:test)